import React from "react";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

const Navbar: React.FunctionComponent = () => {
  return (
    <>
      <nav className={styles.navContainer}>
        <a className={styles.logo}>
          <p>
          All images, logo, name and definition of stoicism were generated by OpenAI and by DALL.E !
          </p>
        </a>
        <ul>
          <li>
            <Link
              className={styles.hoverUnderlineAnimation}
              href="/"
            >
              Quotes
            </Link>
          </li>
          <li>
            <Link
              className={styles.hoverUnderlineAnimation}
              href="/stoicism"
            >
              Stoicism
            </Link>
          </li>
          <li>
            <Link
              className={styles.hoverUnderlineAnimation}
              href="/team"
            >
              The team
            </Link>
          </li>
          <Link
            className={styles.buttonPrimary}
            href="https://github.com/Pierre-LouisDeu/Stoic-Wisdom-Dispenser"
          >
            Ghitub repos
          </Link>
        </ul>
      </nav>
    </>
  );
};

export default Navbar;
