import React from "react";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const Team: React.FunctionComponent = () => {
  return (
    <>
      <div className={styles.teamContainer}>
        <div>
          <h1>Stoics writing their quotes</h1>
          <span>Generated by DALL.E</span>
        </div>
        <section>
          <div className={styles.team}>
            <Image
              src="/assets/dalle1.png"
              className={styles.teamImage}
              alt="headphones"
              width={500}
              height={500}
            />
          </div>
          <div className={styles.team}>
            <Image
              src="/assets/dalle2.png"
              className={styles.teamImage}
              alt="hero"
              width={500}
              height={500}
            />
          </div>
          <div className={styles.team}>
            <Image
              src="/assets/dalle3.png"
              className={styles.teamImage}
              alt="hero"
              width={500}
              height={500}
            />
          </div>
        </section>
      </div>
    </>
  );
};

export default Team;
